const LAC_VIET_QUE = [
    { name: "Đỗ Tiểu Cát", meaning: "Tiểu Cát Mộc sinh Đỗ Hoả. Nội sinh ngoại. Việc thành đạt do cố gắng, Tiểu lợi." },
    { name: "Đỗ Đại An", meaning: "Đỗ Hoả sinh Đại An Thổ. Ngoại sinh nội. Thuận lợi, Tốt. Chủ về Công danh tài lợi." },
    { name: "Đỗ Tốc Hỷ", meaning: "Đỗ Hoả ngang hoà Tốc Hỷ Hoả. Hoà hợp, đồng thuận. Mọi việc tốt đẹp. Chủ về công danh, tiếng tăm, tri tuệ." },
    { name: "Cảnh Xích Khẩu", meaning: "Âm Hoả đới Thổ vừa khắc vừa sinh Xích Khẩu Kim" },
    { name: "Cảnh Vô Vong", meaning: "Âm Hoả đới Thổ sinh Vô Vong Thổ. Ngoại sinh nội. Điều kiện thuận lợi cho hoàn cảnh tự thân vốn không khả quan. Chủ quý nhân phù trợ." },
    { name: "Cảnh Lưu Niên", meaning: "Âm Hoả đới Thổ xung khắc Lưu Niên Thuỷ. Hình thức bên ngoài tốt đẹp không thể hiện nội dung bên trong đang xấu." },
    { name: "Tử Tốc Hỷ", meaning: "Tốc Hỷ Hoả khắc Tử Kim. Nội lục mạnh khắc chế được hoàn cảnh không thuận lợi. Chủ sự cố gắng vượt lên hoàn cảnh." },
    { name: "Tử Tiểu Cát", meaning: "Tử Kim khắc Tiểu Cát Mộc. Hoàn cảnh không thuận lợi. Thiệt hại nhỏ. Chủ tình cảm suy." },
    { name: "Tử Đại An", meaning: "Đại An Thổ sinh Tử Kim. Chủ sinh xuất bất lợi. Sự nghiệp hao tổn, nhưng không đáng kể." },
    { name: "Kinh Lưu Niên", meaning: "Kinh Kim sinh Lưu Niên Thuỷ. Chủ bất ngờ suy bại lớn." },
    { name: "Kinh Xích Khẩu", meaning: "Hai hành Kim ngang hoà. Chủ bất ngờ gây tranh chấp lớn. Về số mệnh tuỳ câu hỏi chủ bất ngờ có tài lộc lớn nhưng không dễ dàng" },
    { name: "Kinh Vô Vong", meaning: "Vô Vong Âm Thổ sinh xuất Kinh Kim. Tượng vàng nổi trên mặt đất. Đem thân dâng hiến cho đời. Tuy có tiêng vang, nhưng việc không thành." },
    { name: "Khai Đại An", meaning: "Đại An Thổ khắc Khai Thuỷ. Tượng nước chảy thông trên mặt đất. Từ từ, thận trong việc thành. Quẻ Dịch tương ứng Thuỷ Địa Sư." },
    { name: "Khai Tốc Hỷ", meaning: "Khai Thuỷ khắc Tốc Hỷ Hoả. Tượng dòng suối đẹp chảy ảo ạt. Mọi việc hanh thông vì tương ứng tính chất tốt của quẻ. Nhưng thành việc phải biết dừng." },
    { name: "Khai Tiểu Cát", meaning: "Khai Thuỷ sinh Tiểu Cát Mộc. Ngoịa sinh nội. Hoàn cảnh tốt cho bản thể. Phát chậm, nhưng chắc chắn." },
    { name: "Hưu Lưu Niên", meaning: "Lưỡng Thuỷ thuỷ triệt. Quẻ xấu, lo buồn thế cuộc, thời vận." },
    { name: "Hưu Xích Khẩu", meaning: "Xích khẩu Kim sinh Hưu Thuỷ tù. Chủ sự lưỡng lự, tranh chấp nôpị bộ và không còn cơ hội." },
    { name: "Hưu Vô Vong", meaning: "Tượng nước chảy ngầm dưới đất. Không dùng được việc gì." },
    { name: "Sinh Đại An", meaning: "Sinh Mộc khắc Đại An Thổ. Tượng bãi cỏ xanh tốt rộng lớn. Quẻ tốt , chậm chắc chắn sẽ thảnh công. Khó khăn không đáng kể." },
    { name: "Sinh Tốc Hỷ", meaning: "Sinh Mộc sinh Tốc Hỷ Hoả. Tượng cỏ khô đốt lửa. Điều kiện tuy thuận lợi nhưng klhông thoả mãn nhu cầu. Nôn nóng thất bại." },
    { name: "Sinh Tiểu Cát", meaning: "Lưỡng Mộc thành Lâm. Quẻ tốt.  Mọi việc tiệm tiến hanh thông, do tính của mộc phát chậm. Phải biết thuận thế phát triển." },
    { name: "Thương Lưu Niên", meaning: "Lưu Niên Thuỷ sinh Thương Mộc. Hoàn cảnh buồn bã, khiến lo lắng không yên. Mưu sự cũng thất bại. Phải chờ đợi." },
    { name: "Thương Xích Khẩu", meaning: "Xích khẩu Kim khắc thương Mộc. Chủ tranh chấp tổn hại. Việc thành nhưng bất lợi về tình." },
    { name: "Thương Vô Vong", meaning: "Thương Mộc khắc Vô Vong Thổ. Tượng nhà tranh xiêu veo, sụp nát. Việc buồn không thành." },
    { name: "Đỗ Lưu Niên", meaning: "Lưu Niên thuỷ khắc Đỗ Hoả. Nội khắc ngoại. Hình thức không phản ánh nội dung. Cẩn thận với hình thức bên ngoài của đối tượng." },
    { name: "Đỗ Xích Khẩu", meaning: "Ngoại khắc nội. Bề ngoài tuy nhiệt tình, nhưng bên trong còn phân vân chưa quyết. Cuối cùng sẽ đạt. Thích hợp với việc tiệc tùng, ăn nhâu, tranh luận, bàn cãi." },
    { name: "Đỗ Vô Vong", meaning: "Ngoại sinh nội. Một kẻ được nâng đỡ nhiệt tình,nhưng nội lực yếu. Cuối cùng không được việc." },
    { name: "Cảnh Tiểu Cát", meaning: "Nội sinh ngoại với ý nghĩa Cảnh Âm Hỏa, Nội khắc Ngoại với ý nghĩa Cảnh Âm Thổ Khôn chính vị. Nếu Hỏa Vượng thì nội sinh ngoại. Hỏa mộ thì nội khắc ngoại. Thích hợp với du lịch, đi chơi xa. Làm ăn xa Tiểu Lợi." },
    { name: "Cảnh Đại An", meaning: "Ngoại sinh nội. Công việc thuận lợi. Lợi kiến Đại Nhân. Sự thăng quan tiến chức, công việc thuận lợi. Diễn tiến chậm như chắc chắn." },
    { name: "Cảnh Tốc Hỷ", meaning: "Nôi sinh Ngoại. Âm Dương tương hợp. Đi xa vui vẻ. Mọi chuyện tốt đẹp, bản thân có hao tổn, nhưng hại nhỏ, lợi lớn." },
    { name: "Tử Lưu Niên", meaning: "Ngoại sinh nội. Kim Sinh Thủy. Hoàn cảnh bi đát, bế tắc dẫn đến bất lợi cho chủ thể. Chủ sự chết chóc, đau buồn. Thích hợp với những việc không chính danh. Nhưng hậu quả cũng rất xấu sau này. Thí dụ như đi buôn lậu. Gặp quẻ này sẽ thoát nạn tức thời. Nhưng cuối cùng sự việc cũng bị phanh phui. Hậu quả nặng nề. Quẻ nqaỳ khuyên người nên thận trọng, cân nhắc, suy nghĩ chín chắn trước khi quyết định công việc. Lợi cho sự im lặng, nghiên cứu, tư duy. Nhưng rất chậm." },
    { name: "Tử Xích Khẩu", meaning: "Nội ngoại ngang hòa. Quẻ Thuần kim. Hình tượng của sự kiện cáo, tranh chấp quyết liệt, chiến tranh tàn khốc. Hùn hạp làm ăn bất lợi, tiền bạc hao tán. Lưu ý: Đây là quẻ xác định cuộc chiến ở Afganixtan giữa Hoa kỳ và Taliban." },
    { name: "Tử Vô Vong", meaning: "Nội sinh ngoại. Hoàn cảnh bế tắc, không được việc. Bi đát , hao tổn. Nhưng cuối cùng vượt qua được." },
    { name: "Kinh Tiểu Cát", meaning: "Ngoại khắc nội. Dương Kim khắc Mộc. Khắc sát Dương Mộc, nhưng không khắc Âm Mộc. Chủ sự bất ngờ liên quan đến, học hành , thi cử, giấy tờ....Sẽ thất tình do sự kiện bất ngờ (Trường hợp tình duyên đang nồng thắm), nhưng có tình duyên bất ngờ, hoặc chuyển biến bất ngờ về tình cảm (Nếu đang bất lợi về tình duyên)." },
    { name: "Kinh Đại An", meaning: "Nội sinh ngoại. Chủ sự bất ngờ ở trong bề trên có lợi cho đương số (Chủ thể coi bói). Động đất lớn nhưng không gây tác hại. Về nhà cửa thì nguy nga tráng lệ." },
    { name: "Kinh Tốc Hỷ", meaning: "Nội Khắc Ngoại. Chủ tin vui bất ngờ. Sự kiện bất ngờ. Nếu đang vui vẻ, gặp quẻ này thì niềm vui không hoàn hảo." },
    { name: "Khai Lưu Niên", meaning: "Quẻ thuần thủy. Tương đương với quẻ thuần Khảm trong Kinh Dịch. Thành đạt nhờ tư duy sâu sắc. Cần thận trọng với chính mình. Vượng vào Xuân Thu." },
    { name: "Khai Xích Khẩu", meaning: "Nội sinh Ngoại. Chủ sự tranh luận thành công, danh tiếng. Thuận cho việc quảng cáo, du lịch, hội thảo, họp mặt; kinh doanh du lịch lữ hành, nhà hàng. Hùn hạp thành công. Đầu tư lúc đầu hao tốn nhưng sau phát triển..." },
    { name: "Khai Vô Vong", meaning: "Nội khắc ngoại. Nhưng Âm Thổ không khắc Dương Thủy. Tượng nước chảy trên lòng sông. Việc hanh thông, nhưng chủ thể không lợi. Tượng của việc làm phúc, từ thiện, nên hậu vận tốt đẹp. Quẻ này tượng cho người quân tử \"Lo trước cái lo của thiên hạ. Vui sau cái vui của thiên hạ\". Kẻ tiểu nhân không dùng được." },
    { name: "Hưu Tốc Hỷ", meaning: "Ngoại khắc nội. Nhưng Âm Thủy không khắc Dương Hỏa. Hình ảnh: Quân tử được thời (Hỏa Vượng), đem điều chính giáo hóa tiểu nhân. Thất thể (Hỏa suy) giữ mình ẩn dật. Lòng không thay đổi." },
    { name: "Hưu Tiểu Cát", meaning: "Ngoại sinh nội. Bế tắc nhất thời. sau tốt. Chủ sự kiên trì sẽ thành công." },
    { name: "Hưu Đại An", meaning: "Nội khắc ngoại. Điều kiện bất lợi. kiên trì sẽ thành công." },
    { name: "Sinh Lưu Niên", meaning: "Nội sinh ngoại. Hoàn cảnh thuận lợi. Nhưng trong lòng hồ nghi, không quyết đoán. Chuyện xấu mới đến. Cần suy ngẫm chín chắn." },
    { name: "Sinh Xích Khẩu", meaning: "Nội khắc ngoại. Việc quyết tâm thì sẽ thành, cần bàn bạc kỹ lưỡng. Lợi đến từ tiền bạc, quan hệ. Cẩn thận tranh chấp cữ cãi liên quan đến giấy tờ." },
    { name: "Sinh Vô Vong", meaning: "Ngoại khắc nội. Ngoại lực yếu không được việc, không khắc được. Hy vọng đến, nhưng việc không thành. Lợi cho việc Thổ mộc (Sửa chữa nhà cửa)." },
    { name: "Thương Tốc Hỷ", meaning: "Ngoại sinh nội. Hoàn cảnh tuy khó khăn, nhưng nhờ trí tuệ và sự trong sáng sẽ thành công. ứng xử vui vẻ. Giống như một người bị chủ nợ đến đòi, tiếp họ vui vẻ, cứ hoàn cảnh thực mà khất nợ, sẽ qua được." },
    { name: "Thương Tiểu Cát", meaning: "Nội ngoại ngang hòa. Vượng vào mùa Đông - Xuân. Hợp Hợi Mão Mùi, Thân Tý Thìn. Chuyện tình cảm buồn. Nhưng có hậu về sau. Sự việc thành nhưng chậm." },
    { name: "Thương Đại An", meaning: "Ngoại khắc nội. lợi việc Thổ Mộc (Xây dựng nhà cửa). Chuyện buồn, thương tổn. Nhưng quẻ nội mạnh sẽ qua." }
];
